In [1]:
import numpy as np

arreglo = np.array([0,1,2,3,4,5])

arreglo, type(arreglo)


notas = [16,17,14,17,19,15]

print(type(notas))
ar_notas = np.array(notas, dtype=float)
print(type(ar_notas))
print(type(ar_notas[0]))

ar_notas_todas = np.array(([0,1,2,3,4,5], notas))
print(ar_notas_todas)

for nodo_nota in ar_notas_todas:
    print(nodo_nota)
    pass

print (ar_notas_todas.ndim)
print (ar_notas.ndim)

print (ar_notas_todas.shape) #cantidad de filas, cantidad de elementos en las filas

<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[[ 0  1  2  3  4  5]
 [16 17 14 17 19 15]]
[0 1 2 3 4 5]
[16 17 14 17 19 15]
2
1
(2, 6)


In [2]:
#09 arrays multidimensionales


zeros = np.zeros((2,3), dtype=int)
print(zeros)

ones = np.ones((3,4), dtype=int)
print(ones)
identity = np.identity((4), dtype=float)
print(identity)
eye = np.eye((5))
print(eye)

arange = np.arange(0,9,2)
arange



[[0 0 0]
 [0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([0, 2, 4, 6, 8])

In [3]:
#10 operaciones con array
arr1 = np.arange (0,11)
arr2 = arr1

arrSuma = arr1 + arr2

arrResta = arr1 - arr2

arrProd = arr1 * arr2

arrExp = arr1 ** arr2

arrDiv = arr1 / arr2


In [4]:
#12 Algebra Lineal

#Producto de arrays
a = np.array([1,2,3], float)
b = np.array([0,1,1],float)

#producto escalar
dotBA = (np.dot(b,a))
dotAB = (np.dot(a,b))
aDotB = (a.dot(b))

#producto de matrices
a = np.array([[5,2],[4,8]],float)
b = np.array([[2,4],[5,3]], float)
dotAB2 = (np.dot(a,b))
aArrobaB = (a@b)
bArrobaA = (b@a)
matmulAB = np.matmul(a,b)


#determinante de una matriz
aDeterminante = np.array([[8,5],[3,4]])
determinante = np.linalg.det(a)

#Auto valores y Auto vectores
autovectores,autovalores = np.linalg.eig(a)



In [5]:
#13 funciones unarias

a = np.array([2,4,9], float)
np.mean(a)
np.sqrt(a)
np.exp(a)
np.log(a)

np.sin(a)
np.median(a)
np.std(a)
np.var(a)

8.666666666666666

In [6]:
arr1 = np.array([5,36,17,18,9])
arr2 = np.array([8,24,17,19,9])

np.add(arr1,arr2)
np.subtract(arr1,arr2)
np.multiply(arr1,arr2)
np.divide(arr1,arr2)
np.array_equal(arr1,arr2)
np.fmin(arr1,arr2)
np.fmax(arr2,arr1)


array([ 8, 36, 17, 19,  9])

In [9]:
#15 gregar y quitar a array
arr = np.arange(0,20,2)
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr_flot = np.random.rand(4,3)